distributionUrl=https\://mirrors.cloud.tencent.com/gradle/gradle-8.5-all.zip

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Memory
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m
org.gradle.daemon=true
org.gradle.parallel=true

# Suppress warnings
android.suppressUnsupportedCompileSdk=35

# Kotlin code style
kotlin.code.style=official

# Additional configurations
android.nonTransitiveRClass=false

